# Site settings
# in the templates available like {{ site.myvariable }}.
title: FOTOS Y PAISAJES
email: 16670322@itiguala.edu.mx.com
brand: FOTOS Y PAISAJES DEL MUNDO
headline: Fotografias y paisajes que te transportan...
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://alejandroalejandrosanchez.github.io/BLOG-PERSONAL/" # the base hostname & protocol for your site
copyright: 2016 Whatever Company, Inc. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

#Contacts
email: 16670322@itiguala.edu.mx
phone: +52 733 1386967

# Tracking
googleAnalitycsID: UA-83933844-1

